Failure # 1 (occurred at 2024-05-20_16-03-59)
[36mray::ImplicitFunc.train()[39m (pid=60964, ip=127.0.0.1, repr=train_tune_parallel)
  File "python\ray\_raylet.pyx", line 830, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 834, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 780, in ray._raylet.execute_task.function_executor
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\ray\tune\trainable\trainable.py", line 367, in train
    raise skipped from exception_cause(skipped)
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\ray\tune\trainable\function_trainable.py", line 335, in entrypoint
    return self._trainable_func(
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\ray\tune\trainable\function_trainable.py", line 652, in _trainable_func
    output = fn()
  File "c:\Users\pietr\OneDrive\Documenti\PIETRO\ETH\SS24\Semester_project\SNN_project\raytune.py", line 219, in train_tune_parallel
    train_loss, train_acc = trainModel(model, train_loader , optimizer, scheduler, criterion, hyperparams, device)
  File "C:\Users\pietr\OneDrive\Documenti\PIETRO\ETH\SS24\Semester_project\SNN_project\util.py", line 498, in trainModel
    loss.backward()
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\torch\_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\torch\autograd\__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\Users\pietr\anaconda3\envs\snnproject\lib\site-packages\torch\autograd\function.py", line 289, in apply
    return user_fn(self, *args)
  File "C:\Users\pietr\OneDrive\Documenti\PIETRO\ETH\SS24\Semester_project\SNN_project\layers.py", line 56, in backward
    return grad_input * hu
UnboundLocalError: local variable 'hu' referenced before assignment
